
project_id = "rxqoczksnddbxcdwobnw"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
external_url = "http://localhost:54324"
jwt_expiry = 3600
refresh_token_rotation_enabled = true
secure_password_change_enabled = true
enable_manual_linking = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[auth.sms]
enable_signup = false
enable_confirmations = false

[storage]
enabled = true
port = 54325
file_size_limit = "50MiB"
file_expiry_duration = "1h"

[edge_functions]
enabled = true
port = 54322

[functions.newsletter-cron]
verify_jwt = false

[functions.send-newsletter-now]
verify_jwt = false

[functions.unsubscribe-newsletter]
verify_jwt = false

[db]
port = 54322
shadow_port = 54320
major_version = 15
