
project_id = "rxqoczksnddbxcdwobnw"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54322
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://rxqoczksnddbxcdwobnw.supabase.co"]
jwt_expiry = 3600
enable_signup = true

[auth.email]
enable_signup = true
enable_confirmations = false

[db]
port = 54323

[storage]
enabled = true
port = 54324
file_size_limit = "50MiB"

[edge_runtime]
enabled = true
port = 54325

[functions.create-checkout-session]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.pawapay-webhook]
verify_jwt = false

[functions.generate-tickets]
verify_jwt = true

[functions.initiate-payment]
verify_jwt = true

[functions.send-order-confirmation]
verify_jwt = true

[functions.send-payment-confirmation]
verify_jwt = true

[functions.send-event-confirmation]
verify_jwt = true

[supabase]
port = 54326
