import React, { useState, useEffect, useNavigate } from 'react';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Progress } from '@/components/ui/progress';
import { toast } from 'sonner';
import { GraduationCap, Award, Download, Share2, RotateCcw, CheckCircle, XCircle } from 'lucide-react';
import { supabase } from '@/lib/supabaseClient';

interface FinalExamResultsModalProps {
  isOpen: boolean;
  onClose: () => void;
  examScore: number;
  quizScores: number[];
  finalGrade: number;
  passed: boolean;
  courseName: string;
  studentName: string;
  enrollmentId: string;
  onRetake: () => void;
}

const FinalExamResultsModal: React.FC<FinalExamResultsModalProps> = ({
  isOpen,
  onClose,
  examScore,
  quizScores,
  finalGrade,
  passed,
  courseName,
  studentName,
  enrollmentId,
  onRetake
}) => {
  const navigate = useNavigate();
  const [certificate, setCertificate] = useState<any>(null);
  const [generatingCertificate, setGeneratingCertificate] = useState(false);

  useEffect(() => {
    if (isOpen && passed) {
      generateCertificate();
    }
  }, [isOpen, passed]);

  const calculateGradeBreakdown = () => {
    const quizAverage = quizScores.length > 0 
      ? quizScores.reduce((sum, score) => sum + score, 0) / quizScores.length 
      : 0;
    
    // Weight: 60% quizzes, 40% final exam (adjust as needed)
    const quizWeight = 0.6;
    const examWeight = 0.4;
    
    return {
      quizAverage: Math.round(quizAverage),
      examScore,
      weightedQuizScore: Math.round(quizAverage * quizWeight),
      weightedExamScore: Math.round(examScore * examWeight),
      finalGrade: Math.round((quizAverage * quizWeight) + (examScore * examWeight))
    };
  };

  const generateCertificate = async () => {
    setGeneratingCertificate(true);
    try {
      // Check if certificate already exists
      const { data: existingCert } = await supabase
        .from('certificates')
        .select('*')
        .eq('enrollment_id', enrollmentId)
        .single();

      if (existingCert) {
        setCertificate(existingCert);
        return;
      }

      // Generate new certificate
      const verificationCode = generateVerificationCode();
      const certificateData = {
        enrollment_id: enrollmentId,
        verification_code: verificationCode,
        pdf_url: null // Will be generated by the certificate service
      };

      const { data: newCert, error } = await supabase
        .from('certificates')
        .insert(certificateData)
        .select()
        .single();

      if (error) throw error;

      setCertificate(newCert);
      toast.success('Certificate generated successfully!');
    } catch (error) {
      console.error('Error generating certificate:', error);
      toast.error('Failed to generate certificate');
    } finally {
      setGeneratingCertificate(false);
    }
  };

  const generateVerificationCode = () => {
    return 'SP-' + Date.now().toString(36).toUpperCase() + '-' + Math.random().toString(36).substr(2, 5).toUpperCase();
  };

  const downloadCertificate = () => {
    // Create a simple HTML certificate for download
    const certificateHTML = createCertificateHTML();
    const blob = new Blob([certificateHTML], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    
    const link = document.createElement('a');
    link.href = url;
    link.download = `${courseName.replace(/\s+/g, '_')}_Certificate.html`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
    
    toast.success('Certificate downloaded successfully!');
  };

  const createCertificateHTML = () => {
    const currentDate = new Date().toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric'
    });

    return `
    <!DOCTYPE html>
    <html>
    <head>
        <title>SkillPulse Certificate</title>
        <style>
            body {
                font-family: 'Georgia', serif;
                margin: 0;
                padding: 40px;
                background: linear-gradient(135deg, #f59e0b 0%, #8b5cf6 100%);
                min-height: 100vh;
                display: flex;
                align-items: center;
                justify-content: center;
            }
            .certificate {
                background: white;
                padding: 60px;
                border-radius: 20px;
                box-shadow: 0 20px 40px rgba(0,0,0,0.1);
                max-width: 800px;
                width: 100%;
                text-align: center;
                border: 8px solid #f59e0b;
                position: relative;
            }
            .certificate::before {
                content: '';
                position: absolute;
                top: 20px;
                left: 20px;
                right: 20px;
                bottom: 20px;
                border: 2px solid #8b5cf6;
                border-radius: 12px;
                pointer-events: none;
            }
            .logo {
                font-size: 2.5rem;
                font-weight: bold;
                background: linear-gradient(45deg, #f59e0b, #8b5cf6);
                -webkit-background-clip: text;
                -webkit-text-fill-color: transparent;
                background-clip: text;
                margin-bottom: 20px;
            }
            .title {
                font-size: 3rem;
                color: #1f2937;
                margin: 20px 0;
                font-weight: normal;
            }
            .subtitle {
                font-size: 1.2rem;
                color: #6b7280;
                margin-bottom: 40px;
            }
            .recipient {
                font-size: 2.5rem;
                color: #f59e0b;
                font-weight: bold;
                margin: 30px 0;
                text-decoration: underline;
                text-decoration-color: #8b5cf6;
            }
            .course {
                font-size: 1.8rem;
                color: #1f2937;
                margin: 30px 0;
                font-style: italic;
            }
            .completion {
                font-size: 1.1rem;
                color: #6b7280;
                margin: 20px 0;
            }
            .score {
                font-size: 1.4rem;
                color: #059669;
                font-weight: bold;
                margin: 20px 0;
            }
            .signature-section {
                margin-top: 50px;
                display: flex;
                justify-content: space-between;
                align-items: flex-end;
            }
            .signature-left {
                flex: 1;
                text-align: left;
            }
            .signature-image {
                max-width: 150px;
                max-height: 80px;
                margin-bottom: 10px;
                display: block;
            }
            .signature-right {
                flex: 1;
                text-align: right;
            }
            .signature-line {
                border-top: 2px solid #1f2937;
                width: 200px;
                margin: 0 auto 10px auto;
                text-align: center;
            }
            .signature-title {
                font-size: 0.9rem;
                color: #6b7280;
                text-align: center;
            }
            .date-section {
                text-align: center;
                margin-top: 30px;
            }
            .verification {
                margin-top: 30px;
                font-size: 0.8rem;
                color: #9ca3af;
                text-align: center;
            }
            .grade-badge {
                display: inline-block;
                background: linear-gradient(45deg, #f59e0b, #8b5cf6);
                color: white;
                padding: 10px 20px;
                border-radius: 25px;
                font-weight: bold;
                margin: 20px 0;
            }
        </style>
    </head>
    <body>
        <div class="certificate">
            <div class="logo">🎓 SkillPulse</div>
            <div class="title">Certificate of Completion</div>
            <div class="subtitle">This is to certify that</div>
            <div class="recipient">${studentName}</div>
            <div class="completion">Has successfully completed the course</div>
            <div class="course">"${courseName}"</div>
            <div class="grade-badge">Final Grade: ${finalGrade}%</div>
            <div class="completion">Demonstrating professional competency and commitment to continuous learning</div>           
            
            <div class="signature-section">
                <div class="signature-left">
                    <img src="https://rxqoczksnddbxcdwobnw.supabase.co/storage/v1/object/public/asset/signature.png" 
                         alt="Authorized Signature" class="signature-image" />
                    <div class="signature-title">Director Learning</div>
                    <div class="signature-title">SkillPulse Technologies Limited</div>
                </div>
                <div class="signature-right">
                    <div class="signature-line"></div>
                    <div class="signature-title">Authorized Signature</div>
                </div>
            </div>
            
            <div class="date-section">
                <div style="font-size: 0.9rem; color: #6b7280;">${currentDate}</div>
                <div style="font-size: 0.8rem; color: #9ca3af; margin-top: 5px;">Date of Completion</div>
            </div>
            
            <div class="verification">
                Verification Code: ${certificate?.verification_code || 'SP-GENERATING'}<br>
                This certificate can be verified at skillpulse.cloud/verify
            </div>
        </div>
    </body>
    </html>
    `;
  };

  const shareOnLinkedIn = () => {
    const text = `I'm excited to share that I've successfully completed "${courseName}" with a final grade of ${finalGrade}%! 🎓 #ProfessionalDevelopment #SkillPulse #ContinuousLearning`;
    const url = `https://www.linkedin.com/sharing/share-offsite/?url=${encodeURIComponent(window.location.origin)}&summary=${encodeURIComponent(text)}`;
    window.open(url, '_blank');
  };

  const breakdown = calculateGradeBreakdown();

  return (
    <Dialog open={isOpen} onOpenChange={onClose}>
      <DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <GraduationCap className="h-6 w-6 text-orange-500" />
            Final Exam Results
          </DialogTitle>
        </DialogHeader>

        <div className="space-y-6">
          {/* Pass/Fail Status */}
          <Card className={`${passed ? 'border-green-200 bg-green-50' : 'border-red-200 bg-red-50'}`}>
            <CardContent className="pt-6">
              <div className="flex items-center gap-3 mb-4">
                {passed ? (
                  <>
                    <CheckCircle className="h-8 w-8 text-green-600" />
                    <div>
                      <h3 className="text-lg font-semibold text-green-800">Congratulations! You Passed!</h3>
                      <p className="text-green-600">You have successfully completed the course</p>
                    </div>
                  </>
                ) : (
                  <>
                    <XCircle className="h-8 w-8 text-red-600" />
                    <div>
                      <h3 className="text-lg font-semibold text-red-800">Not Passed</h3>
                      <p className="text-red-600">You need 70% or higher to pass. You can retake the exam.</p>
                    </div>
                  </>
                )}
              </div>
              
              <div className="text-center">
                <div className="text-3xl font-bold mb-2">
                  <span className={passed ? 'text-green-600' : 'text-red-600'}>
                    {finalGrade}%
                  </span>
                </div>
                <p className="text-sm text-muted-foreground">Final Grade</p>
              </div>
            </CardContent>
          </Card>

          {/* Grade Breakdown */}
          <Card>
            <CardHeader>
              <CardTitle className="text-lg">Grade Breakdown</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="space-y-3">
                <div className="flex justify-between items-center">
                  <span>Final Exam Score:</span>
                  <Badge variant="outline" className="font-mono">
                    {examScore}%
                  </Badge>
                </div>
                
                {quizScores.length > 0 && (
                  <>
                    <div className="flex justify-between items-center">
                      <span>Quiz Average:</span>
                      <Badge variant="outline" className="font-mono">
                        {breakdown.quizAverage}%
                      </Badge>
                    </div>
                    
                    <div className="border-t pt-3">
                      <div className="text-sm text-muted-foreground mb-2">Weighted Calculation:</div>
                      <div className="flex justify-between items-center text-sm">
                        <span>Quizzes (60%):</span>
                        <span>{breakdown.weightedQuizScore}%</span>
                      </div>
                      <div className="flex justify-between items-center text-sm">
                        <span>Final Exam (40%):</span>
                        <span>{breakdown.weightedExamScore}%</span>
                      </div>
                    </div>
                  </>
                )}
                
                <div className="border-t pt-3">
                  <div className="flex justify-between items-center font-semibold">
                    <span>Final Grade:</span>
                    <Badge variant={passed ? "default" : "destructive"}>
                      {finalGrade}%
                    </Badge>
                  </div>
                </div>
              </div>
              
              <Progress value={finalGrade} className="h-3" />
              <div className="flex justify-between text-xs text-muted-foreground">
                <span>0%</span>
                <span className="font-medium">70% (Passing)</span>
                <span>100%</span>
              </div>
            </CardContent>
          </Card>

          {/* Quiz Scores Detail */}
          {quizScores.length > 0 && (
            <Card>
              <CardHeader>
                <CardTitle className="text-lg">Individual Quiz Scores</CardTitle>
              </CardHeader>
              <CardContent>
                <div className="grid grid-cols-2 md:grid-cols-3 gap-3">
                  {quizScores.map((score, index) => (
                    <div key={index} className="text-center p-3 bg-gray-50 rounded-lg">
                      <div className="font-semibold">Quiz {index + 1}</div>
                      <div className="text-lg font-mono">{score}%</div>
                    </div>
                  ))}
                </div>
              </CardContent>
            </Card>
          )}

          {/* Certificate Section */}
          {passed && (
            <Card className="border-orange-200 bg-gradient-to-r from-orange-50 to-purple-50">
              <CardHeader>
                <CardTitle className="flex items-center gap-2 text-orange-800">
                  <Award className="h-5 w-5" />
                  Your Certificate
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                {generatingCertificate ? (
                  <div className="text-center py-4">
                    <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-orange-500 mx-auto mb-2"></div>
                    <p className="text-sm text-muted-foreground">Generating your certificate...</p>
                  </div>
                ) : certificate ? (
                  <>
                    <p className="text-sm text-gray-600">
                      🎉 Your certificate of completion has been generated! This certificate validates your 
                      professional development and can be shared on LinkedIn for CPD credits.
                    </p>
                    
                    <div className="bg-white p-4 rounded-lg border">
                      <div className="text-center">
                        <div className="text-lg font-semibold text-orange-600">Certificate of Completion</div>
                        <div className="text-sm text-gray-600 mt-1">{courseName}</div>
                        <div className="text-xs text-gray-500 mt-2">
                          Verification Code: {certificate.verification_code}
                        </div>
                      </div>
                    </div>
                    
                    <div className="flex gap-2">
                      <Button onClick={downloadCertificate} className="flex-1">
                        <Download className="h-4 w-4 mr-2" />
                        Download
                      </Button>
                      <Button onClick={shareOnLinkedIn} variant="outline" className="flex-1">
                        <Share2 className="h-4 w-4 mr-2" />
                        Share on LinkedIn
                      </Button>
                    </div>
                  </>
                ) : (
                  <Button onClick={generateCertificate} className="w-full">
                    <Award className="h-4 w-4 mr-2" />
                    Generate Certificate
                  </Button>
                )}
              </CardContent>
            </Card>
          )}

          {/* Actions */}
          <div className="flex justify-end gap-3">
            {!passed && (
              <Button onClick={onRetake} variant="outline">
                <RotateCcw className="h-4 w-4 mr-2" />
                Retake Exam
              </Button>
            )}
            <Button
              onClick={() => {
                if (passed) {
                  navigate('/course-results');
                } else {
                  onClose();
                }
              }}
            >
              {passed ? 'Proceed To Course Results' : 'Close'}
            </Button>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
};

export default FinalExamResultsModal;
